version: '3'

services:
  bitnami:
    image: 'bitnami/rabbitmq:latest' # see in https://hub.docker.com/r/bitnami/rabbitmq
    ports:
      - 5672
      - 15672
    volumes:
      - 'bitnami:/bitnami/rabbitmq/mnesia'
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    healthcheck:
      test: rabbitmqctl await_startup
      interval: 1s
    
volumes:
  bitnami:
