
services:
  rabbitmq:
    image: rabbitmq
    hostname: amqp
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitmq-tls: # TODO
    image: rabbitmq
    hostname: amqps
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5671:5671"
      

