
services:
  rabbitmq:
    image: rabbitmq
    hostname: amqp
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  tls:
    image: davidkhala/rabbitmq
    hostname: amqps
    ports:
      - "5671:5671"
      - "15671:15671"

