name: mq
on:
  push:

jobs:
  mq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mq: [activemq, rabbitmq/container, rabbitmq/container/bitnami, solace]
    steps:
      - uses: actions/checkout@main
      - run: docker compose up -d
        working-directory: ${{ matrix.mq }}
      
  broker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        broker: [kafka/bitnami, pulsar, pulsar/standalone, confluent, confluent/all-in-one-kraft]
    steps:
      - uses: actions/checkout@main
      - run: docker compose up -d
        working-directory: ${{ matrix.broker }}
      
