name: mq
on:
  push:

jobs:
  mq:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mq: [activeMQ, rabbitmq/container, rabbitmq/container/bitnami, solace]
    steps:
      - uses: actions/checkout@main
      - run: docker compose up -d
        working-directory: ${{ matrix.mq }}
      
  broker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        broker: [kafka/bitnami, pulsar, pulsar/standalone]
    steps:
      - uses: actions/checkout@main
      - run: docker compose up -d
        working-directory: ${{ matrix.broker }}
  confluent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: ./control.sh
        working-directory: confluent/container/compose
