name: mq
on:
  push:

jobs:
  mq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: docker compose up -d
        working-directory: activeMQ
      - run: docker compose up -d
        working-directory: rabbitmq
      
  kafka:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: docker compose up -d
        working-directory: kafka/bitnami
